version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30
      runas: ubuntu
