name: Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload JAR to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: myspringstudybucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CICD_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CICD_SECREAT_KEY }}
          AWS_REGION: ap-northeast-2
          SOURCE_DIR: build/libs
          DEST_DIR: /

      - name: Trigger CodeDeploy
        uses: webfactory/create-aws-codedeploy-deployment@v1
        with:
          application-name: SpringStudy-CICD
          deployment-group: cicd-springstudy-group
          deployment-config-name: CodeDeployDefault.AllAtOnce
          s3-bucket: myspringstudybucket
          s3-bundle-key: app.jar
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CICD_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CICD_SECREAT_KEY }}
          AWS_REGION: ap-northeast-2
